### ISSUE TITLE
IndexError: index -27 is out of bounds for axis 0 

### ISSUE THREAD

**Issue by 8080git** [folkien/pyStock#44]
if I try to launch with the command:
./stock-viewer.py -n AAPL.US -W -g -r

i have this error:

_IndexError: index -27 is out of bounds for axis 0 with size 19_

the report file is also not generated

to get a daily result, how can I try?

`Traceback (most recent call last):
  File "./stock-viewer.py", line 470, in <module>
    ichimoku.Plot(plot9)
  File "/Users/main/test/pyStock/indicators/ichimoku.py", line 228, in Plot
    self.__plotDayLine(plt, 26)
  File "/Users/main/test//pyStock/indicators/ichimoku.py", line 154, in __plotDayLine
    self.tenkanSen.index[-1-days], self.pmin, self.low.values[-1-days])
  File "/Users/main/test/myenv/lib/python3.7/site-packages/pandas/core/indexes/extension.py", line 238, in __getitem__
    result = self._data[key]
  File "/Users/main/test/myenv/lib/python3.7/site-packages/pandas/core/arrays/datetimelike.py", line 281, in __getitem__
    result = super().__getitem__(key)
  File "/Users/main/test/myenv/lib/python3.7/site-packages/pandas/core/arrays/_mixins.py", line 222, in __getitem__
    result = self._ndarray[key]
IndexError: index -27 is out of bounds for axis 0 with size 19`

**Comment by webbrain-dev** [comment]
Hi! I opened PR #64 to address this. It fixes the `IndexError` in the Ichimoku plot when there isn’t enough data for the lookback, and prevents the run from crashing before the report is generated.
